name: zamzam_erp_solution
description: Zamzam ERP Solution- Flutter + Firebase scaffold (Inventory, Sales, Purchases, Couriers)
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: 0.18.1
  uuid: ^4.3.3
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  pdf: ^3.10.4
  printing: ^5.11.0
  flutter_localizations:
    sdk: flutter

  firebase_messaging: ^14.7.9
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
